{
 "title": "iDRAC exporter",
 "description": "Dashboard for custom prometheus exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(redfish_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Chassis health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_chassis_health{chassis_id=~\"System.*\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "FAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(redfish_chassis_fan_health{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "RAID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_chassis_health{chassis_id!~\"System.*\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Power Supply",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_chassis_power_powersupply_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Power comsumption",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redfish_chassis_power_average_consumed_watts{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chassis Temperature",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_chassis_temperature_sensor_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chassis info",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "redfish_chassis_model_info{chassis_id=~\"System.*\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_system_total_processor_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "targets": [
    {
     "expr": "redfish_system_processor_total_cores{instance=~\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "RAM Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redfish_system_memory_capacity{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "iDRAC status",
   "type": "table",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "redfish_manager_health_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_manager_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Redfish Collector Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redfish_exporter_collector_duration_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chassis State",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "redfish_chassis_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System State",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "redfish_system_state{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "CPU & RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "RAM status",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "redfish_system_memory_capacity{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_memory_health_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_memory_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU status",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "redfish_system_processor_total_cores{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_processor_health_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_processor_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redfish_system_total_processor_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 15 },
   "targets": [
    {
     "expr": "redfish_system_processor_total_cores{instance=~\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CPU Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 15 },
   "targets": [
    {
     "expr": "redfish_system_processor_total_threads{instance=~\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CPU status",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "redfish_system_total_processor_health_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_total_processor_state{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Storage Drive status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "redfish_system_storage_drive_capacity{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_storage_drive_health_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_storage_drive_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "FC status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "redfish_chassis_network_port_health_state{instance=~\"$instance\",network_port_type=\"FibreChannel\"}"
    },
    {
     "expr": "redfish_chassis_network_port_state{instance=~\"$instance\",network_port_type=\"FibreChannel\"}"
    }
   ]
  },
  {
   "title": "RAID info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "redfish_chassis_model_info{chassis_id!~\"System.*\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Storage Device status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "redfish_system_simple_storage_device_health_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_simple_storage_device_state{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Power voltage status",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "redfish_chassis_power_voltage_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_chassis_power_voltage_volts{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Power supply status",
   "type": "table",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 45 },
   "targets": [
    {
     "expr": "redfish_chassis_power_powersupply_health{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_chassis_power_powersupply_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_chassis_power_powersupply_power_input_watts{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Power supply wats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "redfish_chassis_power_powersupply_power_input_watts{instance=~\"$instance\"}",
     "legendFormat": "Power supply {{power_supply_id}}:"
    }
   ]
  },
  { "title": "FAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "FAN status",
   "type": "table",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "redfish_chassis_fan_health{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_chassis_fan_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_chassis_fan_rpm{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "FAN RPM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "redfish_chassis_fan_rpm{instance=~\"$instance\"}",
     "legendFormat": "{{fan}}"
    }
   ]
  },
  {
   "title": "Sensor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "redfish_chassis_temperature_celsius{instance=~\"$instance\"}",
     "legendFormat": "Sensor {{sensor}}:"
    }
   ]
  },
  { "title": "PCIE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "PCIE device status",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "redfish_system_pcie_device_health_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_pcie_device_state{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Network Adapter status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "redfish_chassis_network_adapter_health_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_chassis_network_adapter_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Ethernet Interface status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "redfish_system_ethernet_interface_link_status{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_ethernet_interface_health_state{instance=~\"$instance\"}"
    },
    {
     "expr": "redfish_system_ethernet_interface_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "FC status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "redfish_chassis_network_port_health_state{instance=~\"$instance\",network_port_type=\"FibreChannel\"}"
    },
    {
     "expr": "redfish_chassis_network_port_state{instance=~\"$instance\",network_port_type=\"FibreChannel\"}"
    }
   ]
  }
 ]
}