on: release
name: Build
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: mjavier2k/go-release.action@v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: linux
        CGO_ENABLED: "0"  
        EXECUTABLE_NAME: "redfish_exporter"
        EXECUTABLE_PATH: "./build/redfish_exporter"
        PACKAGE: "."
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: mjavier2k/go-release.action@v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux
        CGO_ENABLED: "0"
        EXECUTABLE_NAME: "redfish_exporter"
        EXECUTABLE_PATH: "./build/redfish_exporter"
        PACKAGE: "."
  release-darwin-386:
    name: release darwin/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: mjavier2k/go-release.action@v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: darwin
        CGO_ENABLED: "0" 
        EXECUTABLE_NAME: "redfish_exporter"
        EXECUTABLE_PATH: "./build/redfish_exporter"
        PACKAGE: "."
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: mjavier2k/go-release.action@v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin
        CGO_ENABLED: "0"
        EXECUTABLE_NAME: "redfish_exporter"
        EXECUTABLE_PATH: "./build/redfish_exporter"
        PACKAGE: "."
  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: mjavier2k/go-release.action@v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: windows
        CGO_ENABLED: "0"
        EXECUTABLE_NAME: "redfish_exporter"
        EXECUTABLE_PATH: "./build/redfish_exporter"
        PACKAGE: "."
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: mjavier2k/go-release.action@v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: windows
        CGO_ENABLED: "0"
        EXECUTABLE_NAME: "redfish_exporter"
        EXECUTABLE_PATH: "./build/redfish_exporter"
        PACKAGE: "."
